apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mediawiki-app
spec:
  selector:
    matchLabels:
      app: mediawiki-app
  replicas: 1
  template:
    metadata:
      labels:
        app: mediawiki-app
    spec:
      containers:
        - name: mediawiki-container
          image: mediawiki
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /var/www/html/LocalSettings.php
              subPath: LocalSettings.php
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-mediawiki-config
