apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mediawiki-db-service
spec:
  type: NodePort
  ports:
    - protocol: 3306
      port: 3306
      targetPort: 30001
  selector:
    app: mediawiki-db