# templates/service-db.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mediawiki-db-srv
  labels:
    app: mediawiki-db
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30001
  selector:
    app: mediawiki-db
