# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mediawiki-srv
  labels:
    app: mediawiki-app
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: mediawiki-app
  type: LoadBalancer
